version: 0.1

phases:
  
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - forever restartall
artifacts:
  type: zip
  paths:
    - './**/*'
    - './appspec.yml'
    - './package.json'
