version: 0.1

phases:
  install:
    commands:
      - npm i npm@7.20.3 -g
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  type: zip
  paths:
    - './**/*'
    - './appspec.yml'
    - './package.json'
