version: 0.1

phases:
  
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - sudo kill -9 `sudo lsof -t -i:3020`
      - forever start -c "npm run start" ./
artifacts:
  type: zip
  paths:
    - './**/*'
    - './appspec.yml'
    - './package.json'
